name: suica_viewer
description: Suica Viewer - Flutter port of the FeliCa IC card reader
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  nfc_manager:
    git:
      url: https://github.com/soralis0912/flutter-nfc-manager.git
  nfc_manager_felica:
    git:
      url: https://github.com/soralis0912/flutter-nfc-manager-felica.git
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  nfc_manager:
    git:
      url: https://github.com/soralis0912/flutter-nfc-manager.git

flutter:
  uses-material-design: true
  assets:
    - assets/station_codes.csv
